modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/GsTio86/PixelmonSync"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="pixelmon"
   mandatory=false
   versionRange="[9.1.11,)"
   ordering="AFTER"
   side="BOTH"